version: '3.8'
services:
  php:
    container_name: centra-php
    build:
      context: ./docker/php
    ports:
      - '9001:9000'
    volumes:
      - .:${DOCKER_DIR}
    extra_hosts:
      - "host.docker.internal:host-gateway"
  nginx:
    container_name: centra-nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    restart: always
    volumes:
      - ./docker/nginx:${DOCKER_DIR}
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./var/log/:/var/log/nginx
    depends_on:
      - php